Add Helper API
vaadin/vaadin-time-picker-flow pull request #101
Opened 2020-07-08 09:25 UTC by anasmi

- Component version `2.4.0-alpha1`
- Implement `HasHelper` interface
- Bump version number by 0.1
- Created tests
- Add demo

Current PR has a client-side error: `vaadin-item` has been already defined

Fixes https://github.com/vaadin/vaadin-time-picker-flow/issues/96

2020-07-08 09:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/vaadin-time-picker-flow?pullRequest=101) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/vaadin-time-picker-flow?pullRequest=101) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/vaadin-time-picker-flow?pullRequest=101) it.</sub>

2020-07-14 07:59 UTC, DiegoCardoso requested changes

2020-07-14 07:59 UTC, DiegoCardoso commented on vaadin-time-picker-flow-demo/pom.xml
>      <parent>
There's a dependency for `vaadin-combo-box-flow` defined on this POM and at the line `54` it sets the version to `3.1-SNAPSHOT`. This should be changed to the one we are bumping in combo-box. So, this PR is blocked by https://github.com/vaadin/vaadin-combo-box-flow/pull/372, as we need that snapshot first in order to proceed with this one.

2020-08-21 14:18 UTC, tomivirkki commented on vaadin-time-picker-flow-demo/pom.xml
>      <parent>
Done

2020-08-21 14:37 UTC, tomivirkki approved these changes

2020-08-24 06:33 UTC, DiegoCardoso approved these changes

2020-08-24 06:33 UTC, merged