fix for LocalTime.now()
vaadin/vaadin-time-picker-flow pull request #28
Opened 2019-03-26 13:26 UTC by svipal

This is just a small fix for https://github.com/vaadin/vaadin-time-picker-flow/issues/15
I don't think it needs a test, but let me know what you think.

2019-03-26 13:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/vaadin-time-picker-flow?pullRequest=28) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/vaadin-time-picker-flow?pullRequest=28) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/vaadin-time-picker-flow?pullRequest=28) it.</sub>

2019-03-26 13:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/vaadin-time-picker-flow?pullRequest=28) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/vaadin-time-picker-flow?pullRequest=28) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/vaadin-time-picker-flow?pullRequest=28) it.</sub>

2019-03-26 15:57 UTC, svipal commented on vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
> +    	LocalTime truncated_value = value.truncatedTo(ChronoUnit.MILLIS);
Done

2019-03-26 20:38 UTC, pleku requested changes
Thanks for the fix. Just added suggestions about the comment - they way you added it with `/**` will make it mess up the javadocs for the method.

2019-03-26 20:54 UTC, svipal commented
I can't see your suggestion, is this what you had in mind ?

2019-03-26 21:00 UTC, pleku approved these changes
Yes, I forgot to publish my comment. This fine. Thanks

2019-03-26 21:01 UTC, pleku approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/28#-:-LavncTXBMNDKn8ghVwV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-03-26 21:16 UTC, merged

2019-04-02 06:52 UTC, ThijsMaenhout commented
This commit breaks the feature of setting NULL values in timepicker:

` public void setValue(LocalTime value) {
    	LocalTime truncated_value = value.truncatedTo(ChronoUnit.MILLIS);
    	super.setValue(truncated_value);
    }
 `

[https://github.com/vaadin/vaadin-time-picker-flow/commit/e1b3a2fc6cd5e1a213a60969e43bf90f3047383f#diff-242f4700b1a3ce7b94bf2092fb36ad88](url)

2019-04-02 10:20 UTC, svipal commented
"I don't think a test is needed" Hahaha.
Will commit a fix. I didn't know there was such a feature, apologies.