Improve error handling in connector: wrap with try catch
vaadin/vaadin-time-picker-flow pull request #51
Opened 2019-07-25 12:24 UTC by yuriy-fix

Connected to https://github.com/vaadin/components-team-tasks/issues/455

2019-08-14 10:17 UTC, samie reviewed
Is there technically a way to have a shared tryCatchWrapper for all the components?

2019-10-03 10:03 UTC, tomivirkki commented
> Is there technically a way to have a shared tryCatchWrapper for all the components?

Should this be added to Flow directly, instead of repeating the same code in every connector? @pleku?

2019-12-04 09:02 UTC, Haprog requested changes
Mostly looks good but I think we could reduce the number of `tryCatchWrapper`s here.

To me it looks like everything is executed via one of these directly:
- `initLazy`
- `timepicker.$connector.setLocale`
- `formatTime`
- `parseTime`

I think everything would be covered even if we remove `tryCatchWrapper` from all other functions here except those 4 (and currently `formatTime` and `parseTime` aren't even wrapped with it but I think they should be).

So after adding the wrapper for `formatTime` and `parseTime` I think it's safe to remove it from these:
- `getAmPmString`
- `anyNumberCharToArabicNumberReplacer`
- `parseMillisecondCharsToInt`
- `getTimeFormatOptions`
- `formatMilliseconds`

Or what do you think?

2019-12-04 09:02 UTC, Haprog commented on vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js
> +            })
This line should end in `;` as it is an assignment. This is the end of:
```js
timepicker.$connector.setLocale = tryCatchWrapper(function (locale) {
```

2019-12-04 09:02 UTC, Haprog commented on vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js
> +                //console.info(locale.toUpperCase() + " AM/PM: " + amString + "/" + pmString + ", separator " + separator);
I think this comment line should be removed (though it was not edited in this PR).

2019-12-04 13:17 UTC, yuriy-fix commented on vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js
> +            })
Updated.

2019-12-04 13:17 UTC, yuriy-fix commented on vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js
> +                //console.info(locale.toUpperCase() + " AM/PM: " + amString + "/" + pmString + ", separator " + separator);
Removed.

2019-12-04 13:20 UTC, yuriy-fix commented
@Haprog, thanks for good suggestions!
I was trying to avoid direct wrapping of `i18n` functions with `tryCatchWrapper` and instead wrap the relative methods in order not to mess-up those with wrappers from other components on the page when debugging.

But actually it makes sense, updated in latest commit.

2019-12-09 10:02 UTC, Haprog approved these changes

2019-12-09 12:41 UTC, merged